feat: 중간 커밋
bluewhalekr/paul-ojt pull request #2
Opened 2022-07-22 10:04 UTC by mongte

tasks
- git repo 생성  / 완료
- 프로젝트 셋팅 / 완료
- githubaction 배포 / 완료
- firebase hosting 배포 / 완료
- 회원가입 화면
  . angularMaterial 을 이용한 화면 구성 완료 / angularfire 를 활용한 firebase auth 적용 
  . 에러 처리시 예외 상황과, 로그인 성공시 세션 유지 작업 아직 안되어 있습니다.
- 로그인 화면
  . angularMaterial 을 이용한 화면 구성 완료 / angularfire 를 활용한 firebase auth 적용 
  . 에러 처리시 예외 상황과, 로그인 성공시 세션 유지 작업 아직 안되어 있습니다.
- angularfire 적용하기 / 완료
- angularMaterial  적용하기 / 완료

* 이후 부터는 task별로 branch 만들어서 개별 pr 날리도록 하겠습니다

2022-07-22 23:36 UTC, niceilm commented
.firebase 폴더는 배포시 임시용으로 생성되는 폴더입니다.
.gitignore 에 추가해주세요~

2022-07-22 23:36 UTC, niceilm commented
모든 메서드와 멤버변수 getter / setter 에 접근자를 추가해주세요.

2022-07-22 23:38 UTC, niceilm commented
tslint 설정을 활성화 해주세요.

https://www.notion.so/aimmo/tslint-bc1a705e9e7449a68c1904deeae7751b

물론 deprecated 되었지만 아직 eslint 설정 방법을 못 찾아서 우선 이걸로 코드 스타일의 일관성을 검사하고 있습니다~

2022-07-22 23:39 UTC, niceilm commented
함수/메서드의 리턴문의 타입도 꼭 챙겨주세요.

2022-07-22 23:41 UTC, niceilm commented on src/app/auth/auth.service.ts
> +        tap((result) => {
Arrow function 의 축약 문법을 최대한 활용하세요.
- 파라미터가 단건이면 소괄호를 생략합니다.
- 메서드 body 가 한줄이면 중괄호는 생략합니다.

모든 코드에 적용 해주세요.

2022-07-22 23:44 UTC, niceilm commented on src/app/functools/formgroup-validators.ts
> +export const removeSpace = (fc: FormControl) => {
리턴 타입을 표현하기에 arrow function 이 힘들기 때문에 유틸 함수의 경우 function 키워드로 정의해서 사용합니다.
arrow function 도 당연히 자주 쓰는데요. 주로 재사용되지 않는 경우에만 쓰이고 있습니다.

2022-07-22 23:45 UTC, niceilm commented on src/app/layouts/layout-board/layout-board.component.ts
> +  constructor() { }
자동으로 생성된 코드도 사용하지 않는 코드는 지워둡니다~

2022-07-22 23:46 UTC, niceilm commented on src/app/pages/dash-board/dash-board.module.ts
> +    RouterModule.forChild([{
한줄로 표현하는데 문제가 없으면 한줄로 표현합니다.
이 코드에서는 DashBoardComponent에 매칭되었다는 정도의 정보 밖에 없어서 줄 바꿈으로 얻는 이점이 따로 없습니다.

2022-07-22 23:47 UTC, niceilm commented on src/app/pages/login/model/login.model.ts
> +export type T_FG_STATUS = keyof typeof FG_STATUS
이런 방식도 좋네요.
간단히 노션에 정리해서 팀 리뷰 시간에 공유도 부탁드려요~

2022-07-22 23:50 UTC, niceilm commented on src/app/pages/login/sign-in/sign-in.component.html
>  <form
한줄로 표현하기 힘들때만 줄바꿈을 해주세요.
`>` 도 줄바꿈을 안하고 있습니다.

줄이 늘어나면 읽어야 할 코드가 늘어납니다.
왠만해서 줄 바꿈을 하지 않고
가로로 너무 긴 경우에 줄 단위당 의미가 구분되는 선에서 줄바꿈을 하고 있습니다~

2022-07-22 23:51 UTC, niceilm commented on src/app/pages/login/sign-in/sign-in.component.ts
> +@AutoUnsubscribe()
이런 방법도 괜찮네요~~

2022-07-22 23:52 UTC, niceilm commented on src/app/pages/login/sign-in/sign-in.component.ts
> +  service$?: Subscription;
postfix로 `$`는 종료되지 않는 스트림에만 사용하고 있습니다.
Subscription에 postfix를 변경이 필요합니다.

2022-07-22 23:52 UTC, niceilm commented on src/app/pages/login/sign-in/sign-in.component.ts
>    ngOnInit(): void {
사용되지 않는 코드는 지워둡니다~

2022-07-22 23:53 UTC, niceilm commented on src/app/pages/login/sign-up/sign-up.component.scss
> +    mat-form-field {
스타일링은 태그에 집적하기 보다는 클래스를 설정해서 해주세요.
태그에 종속되지 않아서 태그 변경시 영향을 줄일수 있어서 운영에 더 이점이 있습니다.

2022-07-22 23:56 UTC, niceilm commented on src/app/pages/login/sign-up/sign-up.component.ts
> +  get roles(): string[] {
템플릿에 접근하는 getter에는 매번 계산하는 로직을 넣지 않습니다.
이 경우 getter가 아니라 멤버 변수로 바꾸는게 연산량을 줄입니다.

```
public readonly roles = Object.keys(ERols);
```

2022-07-22 23:58 UTC, niceilm commented on src/app/pages/login/sign-up/sign-up.component.ts
> +    const { email, confirmPassword, password } = this.fg?.getRawValue()
여기서 undefined 리턴이 예상되는데요. 
destructuring 문법을 쓰면 예외가 발생될수 있습니다.
`?? {}` 을 넣어주거나 이 메서드 실행시 명확하게 fg가 존재하면 `this.fg!.` 로 써도 될듯합니다~

2022-07-22 23:59 UTC, niceilm commented on src/app/shared/directives/input-regxp/input-regexp.directive.ts
> +      distinctUntilChanged((p, c) => p === c)
이 경우 파라미터 영역은 생략 가능합니다.

2022-07-23 00:01 UTC, niceilm commented on src/app/shared/directives/input-regxp/input-regexp.directive.ts
> +    this.ngControl$ = this.ngControl.valueChanges?.pipe(
this.ngControl.valueChanges 가 undefined인 경우가 있을까요?
그렇지 않다면 `?` 옵셔널 체이닝을 넣어주지 않아도 될듯합니다.

2022-07-23 00:02 UTC, niceilm commented on src/app/app.module.ts
> +    TranslateModule.forRoot({
벌써 다국어 까지!! 후딱 OJT 끝내고 재미난 실무해요 ㅎㅎ

2022-07-23 00:03 UTC, niceilm commented on src/app/app.module.ts
> +    {provide: LocationStrategy, useClass: HashLocationStrategy},
혹시 HashLocationStrategy 이걸 사용한 이유가 있을까요?

2022-07-23 00:06 UTC, niceilm commented
리뷰 완료했습니다~
2주간 고생 많으셨고요.
리뷰 내용 수정되면 이모지로 체크해주시면 이 브랜치에 커밋시 의도한 대로 수정되었는지 확인 후 resolve 할께요~

2022-07-23 04:10 UTC, mongte commented on src/app/pages/login/model/login.model.ts
> +export type T_FG_STATUS = keyof typeof FG_STATUS
트리쉐이킹 관련 내용인데 저번에 말씀해주신데로 성능상 그렇게 크게 개선되는 부분이 아니라 편의성으로 봤을때 그냥 enum으로 해도 문제없을거같습니다
그냥 이런 방법도 있지 안을까 작성해 봤습니다.

2022-07-23 04:11 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.html
>  <form
vue에서의 컨벤션이라 습관처럼 사용했습니데 수정해두도록 하겠습니다

2022-07-23 04:16 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.ts
> +@AutoUnsubscribe()
회사코드를 보니  컴퍼넌트에서 쓰는 모든 옵저블을 생성자단에서 (생성자, oninit) forkjoin을 써서 takeUntil를 써서 구독을 해지걸로 봤습니다.
예전 앵귤러를 썻을때 구독해지에 대한 고민을 하다가 만든건데 한번 적용 해보았습니다
하다보니 전에 말씀해주신데로 컴퍼넌트 안에서 구독이 1개 이상 발생 할 경우 컴퍼넌트를 쪼개는 방법으로 가면 더 코드가 직관적이 될거같습니다

2022-07-23 04:23 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.ts
> +  service$?: Subscription;
구독을 하는 Subscription 변수에는 $를 넣는걸로 생각했는데 그렇다면 그냥 빼는게 나을까요?
service$?: Subscription; -> subscribe?: Subscription;

그리고 변수명을 특정한 고유명사로 지정한건 컴퍼넌트 하나당 하나의 subscribe만 존재한다면 비즈니스적인 네이밍이 필요 없다고 판단했는데 이런 방법은 어떤지도 피드백 부탁드립니다!.

2022-07-23 04:24 UTC, mongte commented on src/app/pages/login/sign-up/sign-up.component.ts
> +    const { email, confirmPassword, password } = this.fg?.getRawValue()
생각해보니 ?는 오해를 가져올거같습니다.
this.fg! 로 바꾸도록 하겠습니다.!

2022-07-23 04:26 UTC, mongte commented on src/app/app.module.ts
> +    {provide: LocationStrategy, useClass: HashLocationStrategy},
삭제하도록 하겠습니다.
잘못 들어간거같아요

2022-07-23 05:29 UTC, mongte commented
넵 gitignore에 추가해서 제외 시키도록 하겠습니다

2022-07-23 05:32 UTC, mongte commented on src/app/auth/auth.service.ts
> +  signUp<T>(email: string, password: string): Observable<UserCredential> {
넵

2022-07-23 05:33 UTC, mongte commented on src/app/auth/auth.service.ts
> +      .pipe(
넵

2022-07-23 05:33 UTC, mongte commented on src/app/auth/auth.service.ts
> +        tap((result) => {
넵

2022-07-23 05:41 UTC, mongte commented on src/app/functools/formgroup-validators.ts
> +export const removeSpace = (fc: FormControl) => {
넵 
에로우 평션의 경우 this자체가 상위 부모를 바라보기에 컴퍼넌트나 클래스 내에서 메서드로써 자주 사용 했엇는데 말씀하신 재사용이 되자 않은경우라고 하신다면 람다처럼 쓴다고 생각해도 될가요

2022-07-23 05:41 UTC, mongte commented on src/app/layouts/layout-board/layout-board.component.ts
> +  constructor() { }
넵

2022-07-23 05:41 UTC, mongte commented on src/app/pages/dash-board/dash-board.module.ts
> +    RouterModule.forChild([{
넵

2022-07-23 05:42 UTC, mongte commented on src/app/pages/login/model/login.model.ts
> +export type T_FG_STATUS = keyof typeof FG_STATUS
트리쉐이킹 관련 내용인데 저번에 말씀해주신데로 성능상 그렇게 크게 개선되는 부분이 아니라 편의성으로 봤을때 그냥 enum으로 해도 문제없을거같습니다
그냥 이런 방법도 있지 안을까 작성해 봤습니다.

2022-07-23 05:42 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.html
>  <form
넵 vue에서의 컨벤션이라 습관처럼 사용했습니데 수정해두도록 하겠습니다

2022-07-23 05:43 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.ts
> +@AutoUnsubscribe()
회사코드를 보니 컴퍼넌트에서 쓰는 모든 옵저블을 생성자단에서 (생성자, oninit) forkjoin을 써서 takeUntil를 써서 구독을 해지걸로 봤습니다.
예전 앵귤러를 썻을때 구독해지에 대한 고민을 하다가 만든건데 한번 적용 해보았습니다
하다보니 전에 말씀해주신데로 컴퍼넌트 안에서 구독이 1개 이상 발생 할 경우 컴퍼넌트를 쪼개는 방법으로 가면 더 코드가 직관적이 될거같습니다

2022-07-23 05:43 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.ts
> +  service$?: Subscription;
구독을 하는 Subscription 변수에는 $를 넣는걸로 생각했는데 그렇다면 그냥 빼는게 나을까요?
service$?: Subscription; -> subscribe?: Subscription;

그리고 변수명을 특정한 고유명사로 지정한건 컴퍼넌트 하나당 하나의 subscribe만 존재한다면 비즈니스적인 네이밍이 필요 없다고 판단했는데 이런 방법은 어떤지도 피드백 부탁드립니다!.

2022-07-23 05:43 UTC, mongte commented on src/app/pages/login/sign-in/sign-in.component.ts
>    ngOnInit(): void {
넵

2022-07-23 05:44 UTC, mongte commented on src/app/pages/login/sign-up/sign-up.component.scss
> +    mat-form-field {
넵

2022-07-23 05:44 UTC, mongte commented on src/app/pages/login/sign-up/sign-up.component.scss
> +    mat-form-field {
넵

&__mat-form-field

2022-07-23 05:45 UTC, mongte commented on src/app/pages/login/sign-up/sign-up.component.ts
> +  get roles(): string[] {
넵

2022-07-23 05:45 UTC, mongte commented on src/app/pages/login/sign-up/sign-up.component.ts
> +    const { email, confirmPassword, password } = this.fg?.getRawValue()
생각해보니 ?는 오해를 가져올거같습니다.
this.fg! 로 바꾸도록 하겠습니다.!

2022-07-23 05:48 UTC, mongte commented on src/app/shared/directives/input-regxp/input-regexp.directive.ts
> +    this.ngControl$ = this.ngControl.valueChanges?.pipe(
넵 undefined일 케이스는 없습니다!

2022-07-23 05:49 UTC, mongte commented on src/app/shared/directives/input-regxp/input-regexp.directive.ts
> +      distinctUntilChanged((p, c) => p === c)
x => x.replace(new RegExp(this.regexp), '') 로 처리하겠습니다.!

2022-07-23 05:50 UTC, mongte commented on src/app/app.module.ts
> +    {provide: LocationStrategy, useClass: HashLocationStrategy},
잘못 들어갔습니다! 삭제할게요

2022-07-23 05:50 UTC, mongte commented on src/app/app.module.ts
> +    TranslateModule.forRoot({
예압! 후딱끝내겠습니다

2022-07-25 05:42 UTC, niceilm commented
.gitignore 추가만 되었는데요.
 git 에서 해당 폴더의 추적도 삭제 해둬야 할듯해요~
 체크 아웃 받으면 계속 보여서요.

2022-07-25 05:42 UTC, niceilm requested changes
A concern was raised

2022-07-26 10:17 UTC, niceilm approved these changes

2022-07-27 01:29 UTC, merged