feat: service worker admin 적용
bluewhalekr/paul-ojt pull request #24
Opened 2022-08-25 07:38 UTC by mongte

2022-08-28 02:27 UTC, niceilm commented on src/app/core/localforage/localforage.service.ts
> +    return defer(() => this.DB[dbName]?.ready());
구독 시점에 undefined 일 경우에 대한 대응이 없습니다.
undefined 일 경우 createDB 메서드를 호출한 이후에 ready를 호출 할수 있게 해주면 될듯합니다.

2022-08-28 02:28 UTC, niceilm requested changes
리뷰 완료했습니다.
리뷰 내용 확인 부탁합니다.

2022-08-29 02:03 UTC, mongte commented on src/app/core/localforage/localforage.service.ts
> +    return defer(() => this.DB[dbName]?.ready());
* this.DB[dbName]가  undefined 라는건 생성을 안하거나 잘못된 이름으로 넘겨준걸로 보기 때문에 에러를 발생시키는것으로 처리했습니다
* 호출할려는 디비가 undefind일 경우 임의로  createdDb를 내부에서 실행 할 경우 제어권 역전 현상이 일어나 관리포인트가 늘어날 수도 있지 않을까하여 에러로 처리했는데 어떨까요

2022-08-29 03:45 UTC, niceilm commented on src/app/core/localforage/localforage.service.ts
> +    return defer(() => this.DB[dbName]?.ready());
네 말씀해주신 케이스라면 에러를 발생하도록 해주는게 제일 좋을듯합니다.
현재는 에러가 발생하지 않도록 해둔거 같아서 의견 드렸어요.

2022-08-29 03:46 UTC, niceilm approved these changes
수정 내용 모두 확인했습니다~

2022-08-29 04:15 UTC, merged