feat: angular/fire auth, store 적용
bluewhalekr/paul-ojt pull request #3
Opened 2022-07-26 08:00 UTC by mongte

- firebase functions 세팅
- angular/fire
  - user auth, user crud
-

2022-07-26 10:44 UTC, niceilm commented
ui-debug.log 의 경우 개발할때 생성되는 파일 같은데요.
.gitignore 에 추가해주세요~

2022-07-26 10:46 UTC, niceilm commented on src/app/pages/error/error.component.ts
> +
모든 파일에 접근 제한자를 챙겨주세요.
리턴 타입도 챙겨주세요~

2022-07-26 10:48 UTC, niceilm commented
이 버튼의 경우 링크 이동이네요.
a 태그와 routerLink 디렉티브를 활용해주세요~

https://www.notion.so/aimmo/A-RouterLink-d4e2b12122b14fd98c435a5d1d473075

2022-07-26 10:51 UTC, niceilm commented
접근 제한자와 리턴 타입도 챙겨주세염~

2022-07-26 10:52 UTC, niceilm commented
arrow function 축약 문법을 활용해주세요.

2022-07-26 10:52 UTC, niceilm commented
변수명이 user 모델을 담는듯 합니다. 
Subscription을 담는 느낌을 주도록 변경이 필요합니다~

2022-07-26 11:01 UTC, niceilm commented
접근 제한자 리턴 타입을 챙겨주세요~

2022-07-26 11:27 UTC, niceilm requested changes
A concern was raised

2022-07-27 10:28 UTC, niceilm commented
가장 큰 차이점은 한번만 탐색을 해서 성능상 이점이 있습니다.
설정을 안하면 static: false 가 기본이라고 하는데요.
이때는 CD 마다 찾는다고 합니다.

그리고 *ngIf 같은 케이스가 아니라는 것을 나타내기도 합니다.
그리고 ngOnInit 에서 접근이 가능하다고 하고요.
다른 케이스는 ngAfterViewInit 에서 접근이 가능하다고 합니다.

https://stackoverflow.com/questions/56359504/how-should-i-use-the-new-static-option-for-viewchild-in-angular-8

2022-07-27 10:30 UTC, niceilm commented
까먹지 않게 asana 태스크로 만들어서 처리 해주세요~~

2022-07-27 10:30 UTC, niceilm commented on src/app/layouts/layout-board/layout-board.component.ts
> -export class LayoutBoardComponent { }
`@ViewChild 같은 데코레이터를 써도 접근 제한자를 챙겨주는 습관을 만들어 보아요~`

2022-07-27 10:31 UTC, niceilm commented
메서드 바디가 한줄이면 중괄호 생략도 가능합니다~

2022-07-27 10:33 UTC, niceilm commented
메서드 바디가 한줄이면 중괄호 생략도 가능합니다~

2022-07-27 10:47 UTC, niceilm commented
체크 아웃 받았더니 ui-debug.log 도 계속 있네요.
삭제 후 커밋도 필요하네요~

2022-07-29 03:46 UTC, niceilm commented
@{4fe2b078-81e4-481a-acf9-3e9fbb0939c6,paul} 혹시 남은 리뷰의 수정 진행은 어떻게 되고 있을까요?

2022-07-29 03:47 UTC, niceilm commented
그리고 머지된 업소스 리뷰는 클로즈 해주세염~

2022-07-29 10:46 UTC, niceilm commented
보통 네이밍을 할때 타입으로 이름을 정하고요.
여러개가 될 경우 추가 설명을 넣습니다.
현재 이 컴포넌트에서는 Subscription 이 한개라서 아래처럼 네이밍을 해도됩니다.

`private subscription!: Subscription;`

2022-07-29 10:48 UTC, niceilm commented
간소화 하면 아래 처럼 가능합니다~

```
switchMap(({ user }) => defer(() => this.usersDB.add({
          role,
          uid: user?.uid,
          email: user?.email,
          createAt: format(new Date(), 'yyyy-MM-dd hh:mm:ss'),
          useActivate: true
        })))
```

2022-07-29 10:49 UTC, niceilm commented
혹시 여기에 'item' 을 넣는 이유는 있을까요?

2022-07-29 10:55 UTC, niceilm commented
현재는 굳이 exhaustMap 오퍼레이터가 아니여도 tap 오퍼레이터여도 될듯한데요.
위 케이스는 비동기 작업 요청 후 기다림 없이 페이지 이동이 되는데요. 
만약 비동기 작업을 모두 완료 후 페이지 이동이 필요하면 다른 방법이 필요합니다.

2022-07-29 10:58 UTC, niceilm commented
코드 서식 중에 순서도 있는데요.
자동으로 적용이 안된듯합니다~
웹스톰 설정 확인 부탁해요~

2022-07-29 11:02 UTC, niceilm commented
paramMap 을 활용하는 방식이 유지보수성이 더 좋습니다~

2022-07-29 11:05 UTC, niceilm commented
Subject를 직접 노출하지 않습니다.
외부에서 .next 메서드를 호출할수 여지를 두는건 유지보수성이 나빠집니다.

2022-07-29 11:05 UTC, niceilm commented
arrow function

2022-07-29 11:06 UTC, niceilm commented
이렇게 사용하면 좋고요.
여기에 네이밍을 postfix 로 `$` 를 사용하고
내부 변수에서는 postfix로 `Source`를 사용합니다.

2022-07-29 11:07 UTC, niceilm commented
아래 API 의 리턴이 한번 값 발생후 완료가 되지 않는다면
postfix 로 `$`를 붙여주세요.

2022-07-29 11:08 UTC, niceilm commented
Promise는 지양합니다.
혹시 쓰더라도 return 을 꼭 해서 비동기를 컨트롤 할수 있게 해줍니다.

2022-07-29 11:08 UTC, niceilm commented
타입을 지정해줍니다.

2022-07-29 11:09 UTC, niceilm commented
promise는 지양합니다.
쓰더라도 비동기를 컨트롤 할수 있게 return 을 해줍니다.

2022-07-29 11:10 UTC, niceilm commented
prefix로 붙은 service는 불필요해 보입니다~

2022-07-29 11:10 UTC, niceilm commented
접근 제한자를 챙겨주세요.

2022-07-29 11:10 UTC, niceilm commented
routerLink는 가능한 a 태그와 함께 사용합니다~

2022-07-29 11:11 UTC, niceilm commented
코드 서식을 자동으로 적용되도록 웹스톰 설정을 확인해주세요.

2022-07-29 11:12 UTC, niceilm commented
사용되는 곳이 없습니다.

2022-07-29 11:12 UTC, niceilm commented
여기도 할당되는 값이 없습니다.

2022-07-29 11:13 UTC, niceilm commented
사용되는 곳이 없습니다.

2022-07-29 11:13 UTC, niceilm commented
템플릿에서 이 멤버 변수에 접근하는 경우가 있을까요?

2022-07-29 11:14 UTC, niceilm commented
arrow function

2022-07-29 11:14 UTC, niceilm commented
이 파일도 서식 지정이 필요합니다.

2022-07-29 11:15 UTC, niceilm commented
주석은 삭제합니다.
필요한 주석은 이유를 함께 남깁니다.

2022-07-29 11:15 UTC, niceilm commented
console.log 도 지웁니다.
필요한 경우 추가 주석으로 설명을 남겨줍니다.

2022-07-29 11:16 UTC, niceilm commented
사용되지 않는 import 는 지웁니다.

2022-07-29 11:17 UTC, niceilm commented
arrow function

2022-07-29 11:20 UTC, niceilm commented
고생하셨습니다. 추가 리뷰도 모두 완료되었습니다~

기존에 작업 했던 곳에서 이어서 하기 때문에  이미 리뷰 했던 부분과 새롭게 추가된 부분 구분이 힘듭니다.
차후 PR 은 작은 단위로 부탁합니다.
리뷰가 되면 리뷰 처리를 우선 순위를 높여서 진행해주세요.

2022-07-29 11:24 UTC, mongte commented
props. 이름을 그대로 적어준건데 필요없으면 삭제하겠습니다!

2022-07-29 11:32 UTC, mongte commented
처음에는 activatedRoute.paramMap을 구독해서 받아왔는데요 구독을 안하고도 받아올수 있는 방법이 있지 않을까 하고 수정한 부분인데 paramMap으로 수정해 두겟습니다. 구독 하나 하나가 스트림으로 감시가 걸려있다고 생각되니 자연스럽게 줄이는게  좋지 않을까라고 방어적으로 생각한거같습니다.

2022-07-29 11:37 UTC, mongte commented
this.dashBoardDB.doc(id).update(condition) 여기서 더 해줄게 없는 코드인데 워링이 떠서 체이닝 .then()을 추가했습니다
리턴이 필요 없는건 this.dashBoardDB.doc(id).update 시 this.dashBoardDB.valueChange() 가 실행되어 뺏습니다
워링이 문제 없다면 this.dashBoardDB.doc(id).update(condition) then은 빼겠습니다!

2022-07-29 11:40 UTC, mongte commented
템플릿쪽에서 쓴다고 착각한거같습니다. 실수로 넣은거같아요  private로 변경해두도록하겠습니다

2022-07-29 11:46 UTC, niceilm commented
Promise나 Observable을 사용할때에는 항상 return 을 해주면 비동기를 컨트롤 할수 있게 됩니다.

**Promise를 리턴하지 않는 케이스**
```
this.someService.updateBoardDetail();
console.log('이 내용은 업데이트 완료되기 전에 실행됩니다.');
```

**Promise를 리턴하는 케이스**
```
this.someService.updateBoardDetail().then(() => console.log('이 내용은 업데이트 완료된 이후 실행됩니다.'));
```

추가적으로 예외 처리도 가능하고요.
Observable도 위와 비슷합니다.

2022-08-01 04:53 UTC, niceilm commented
위의 tslint:disable-next 도 이제 뺄수 있습니다~

2022-08-01 04:55 UTC, niceilm commented
혹시 `@ts-ignore` 는 어떤 이유로 들어갔을까요?

2022-08-01 05:15 UTC, niceilm commented
메서드 바디가 한줄이면 중괄호 생략이 가능합니다~

2022-08-01 05:18 UTC, niceilm commented
아직 수정이 안된듯합니다~

2022-08-01 05:18 UTC, niceilm commented
추가 리뷰도 완료했습니다~~

2022-08-01 06:23 UTC, niceilm commented
혹시 아래 처럼 변경하면 paramMap 으로 동작이 가능할까요?
![file](https://fe-review.bluewhale.kr/~uploads/paul-ojt/8E5937A2BB25C3E90221769CEA947739B9F146AA-upload-1659334316085.png)

2022-08-01 07:01 UTC, merged