feat: 관리자 권한 기능
bluewhalekr/paul-ojt pull request #8
Opened 2022-08-11 05:25 UTC by mongte

* 관리자 권한 수정 메뉴추가
* 관리자 수정 삭제 생성
* 작업 하다보니 pr 나눠서 하는걸 깜빡 했습니다 죄송합니다

2022-08-11 06:45 UTC, niceilm commented
`routerLink="/admin/dash-board"`
위와 같이 간소화도 가능합니다~

2022-08-11 06:47 UTC, niceilm commented
여기는 조회가 아닌 변경이니 exhaustMap 이 더 자연스러운거 같습니다~

2022-08-11 06:48 UTC, niceilm commented
현재는 아래 스트림 오류 발생시 스트림이 끊깁니다~

2022-08-11 06:49 UTC, niceilm commented
여기도 `routerLink="/dash-board"` 로 간소화 가능합니다~

2022-08-11 06:55 UTC, niceilm commented
메서드명의 경우 동사 + 명사가 되도록 변경해주세요~

2022-08-11 07:00 UTC, niceilm commented
접근 제한자가 누락되었네요~

2022-08-11 07:02 UTC, niceilm commented
module 과 component 단위가 1:1 로 되는걸 추천드립니다~

2022-08-11 07:04 UTC, niceilm commented
condition 개수만큼 tap 이 호출될텐데요.
혹시 모두 완료된 다음 한번만 호출되게 하려면
toArray 오퍼레이터를 참고하셔요~

2022-08-11 07:04 UTC, niceilm commented
혹시 map 메서드는 어떠세요?

2022-08-11 07:05 UTC, niceilm commented
제네릭 타입을 정의 했는데요.
any 보다는 T를 쓰면 되지 않을까요?

2022-08-11 07:05 UTC, niceilm commented
getter를 이용해서 템플릿은 최대한 간소화 될수 있게 해주시면 좋습니다~

2022-08-11 07:06 UTC, niceilm commented
그러고보니 다국어는 했는데 자동으로 추출되는것도 적용해보셨나요?
아니라면 다른 태스크로 다국어 자동추출도 세팅 해보세요~

2022-08-11 07:07 UTC, niceilm commented
생성된 코드라서 접근 제한자가 누락되었네요^^

2022-08-11 07:09 UTC, niceilm commented
현재 구조는 따당을 막을수가 없어요~ㅋ

2022-08-11 07:09 UTC, niceilm commented
현재 구조는 따당을 막을수가 없어요~

2022-08-11 07:10 UTC, niceilm requested changes
A concern was raised

2022-08-14 06:35 UTC, niceilm commented on src/app/pages/login/sign-up/sign-up.component.ts
> +
exhaustMap 으로 처리하고 있어서 debouceTime 은 필요 없을듯합니다~

2022-08-14 07:11 UTC, niceilm commented
아 이 부분은 제가 ngFor 문을 놓쳤네요.
기존 처럼 해도 되고 지금 처럼 메서드를 만들어서 해도 괜찮네요.

2022-08-14 07:12 UTC, niceilm commented
private signOut() 에 `@GlobalCatchError`를 넣어도 스트림의 종료를 막지 못합니다.
스트림 내부를 메서드로 분리하고 그 메서드에 `@GlobalCatchError`를 데코레이팅해서 에러 발생시 스트림이 종료되지 않도록 해야 합니다.

2022-08-14 07:16 UTC, niceilm commented on src/app/pages/admin/authority/providers/authority.service.ts
> +  public userList$<T>(): Observable<T[]> {
사용하지 않는 경우는 제거해두면 좋습니다.

2022-08-14 07:23 UTC, niceilm commented
`permissionUpdate` 메서드가 두개 이상의 condition 값이 있으면 두번 이상의 값이 방출이 되는데요.
사용하는 코드에서는 값이 방출되면 라우터 이동이 되도록 되어 있네요.
모든 값이 업데이트 완료후 이동되게 하는게 좋을듯하고요.
그럴때 toArray 오퍼레이터를 사용하면 좋습니다~

2022-08-14 07:24 UTC, niceilm commented on src/app/pages/admin/admin-dash-board/admin-dash-board.component.ts
> +      root: this.scrollObserver.nativeElement
arrow function 축약이 가능합니다~

2022-08-14 07:25 UTC, niceilm commented
추가 리뷰도 완료했습니다~

2022-08-16 06:12 UTC, mongte commented
커링으로 caught 리턴 여부를 옵셔널하게 바꿀 수 있게 수정해봤는데 확인 부탁드립니다

2022-08-16 08:23 UTC, niceilm commented
체크 아웃 받아서 잠깐 테스트 해봤는데요.
파라미터로 나누기에는 사용되는 위치가 명확하게 달라야 되어서 다른 데코레이터로 구분하는게 더 좋을듯합니다.

실제 운영 업무 할때 관련해서 연구할수 있는 시간 드릴께요. 
일단 이 부분은 빠르게 넘어 가도록 하시죠~

2022-08-16 08:39 UTC, niceilm approved these changes

2022-08-16 09:30 UTC, merged